const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  reloadCurrent: () => ipcRenderer.invoke('reload:current'),
  reloadAll: () => ipcRenderer.invoke('reload:all'),
  onReloadCurrent: (cb) => ipcRenderer.on('reload-current', () => cb()),
  onReloadAll: (cb) => ipcRenderer.on('reload-all', () => cb()),
  getConfig: () => ipcRenderer.invoke('config:get'),
  saveConfig: (cfg) => ipcRenderer.invoke('config:save', cfg),
  listModels: () => ipcRenderer.invoke('models:list'),
  saveModels: (models) => ipcRenderer.invoke('models:save', models),
  openBrowser: (modelId) => ipcRenderer.invoke('browser:open', modelId),
  closeBrowser: (modelId) => ipcRenderer.invoke('browser:close', modelId),
  hideBrowser: () => ipcRenderer.invoke('browser:hide'),
  reloadBrowser: (modelId) => ipcRenderer.invoke('browser:reload', modelId),
  navigateBrowser: (modelId, url) => ipcRenderer.invoke('browser:navigate', modelId, url),
  openExternal: (url) => ipcRenderer.invoke('browser:openExternal', url),
  setSidebarWidth: (w) => ipcRenderer.invoke('browser:setSidebarWidth', w),
  minimize: () => ipcRenderer.invoke('window:minimize'),
  maximize: () => ipcRenderer.invoke('window:maximize'),
  close: () => ipcRenderer.invoke('window:close'),
  isMaximized: () => ipcRenderer.invoke('window:isMaximized'),
  getLogs: () => ipcRenderer.invoke('logs:get'),
  clearLogs: () => ipcRenderer.invoke('logs:clear'),
  copyLogs: () => ipcRenderer.invoke('logs:copy'),
  listHistory: () => ipcRenderer.invoke('history:list'),
  addHistory: (entry) => ipcRenderer.invoke('history:add', entry),
  clearHistory: () => ipcRenderer.invoke('history:clear'),
  listRules: () => ipcRenderer.invoke('rules:list'),
  saveRules: (rules) => ipcRenderer.invoke('rules:save', rules),
  getPrefs: () => ipcRenderer.invoke('prefs:get'),
  savePrefs: (prefs) => ipcRenderer.invoke('prefs:save', prefs),
  translateRequest: (params) => ipcRenderer.invoke('translate:request', params),
  getAllLogos: () => ipcRenderer.invoke('logos:getAll'),
  getLogo: (modelId) => ipcRenderer.invoke('logos:get', modelId),
  fetchLogoForModel: (model) => ipcRenderer.invoke('logos:fetchForModel', model),
  refreshAllLogos: () => ipcRenderer.invoke('logos:refreshAll'),
  onLogosUpdated: (cb) => ipcRenderer.on('logos:allUpdated', () => cb()),
  onLogoUpdated: (cb) => ipcRenderer.on('logos:updated', (_, data) => cb(data)),
  // Ad blocker stats
  getAdBlockStats: () => ipcRenderer.invoke('adblock:stats'),
  resetAdBlockStats: () => ipcRenderer.invoke('adblock:reset'),
  // Updater
  checkForUpdate: () => ipcRenderer.invoke('updater:check'),
  installUpdate: (data) => ipcRenderer.invoke('updater:install', data),
  getVersion: () => ipcRenderer.invoke('updater:version'),
  onUpdateAvailable:  (cb) => ipcRenderer.on('updater:available',          (_, d) => cb(d)),
  onUpdateProgress:   (cb) => ipcRenderer.on('updater:download-progress',  (_, d) => cb(d)),
  onUpdateComplete:   (cb) => ipcRenderer.on('updater:download-complete',  (_, d) => cb(d)),
  onUpdateInstalling: (cb) => ipcRenderer.on('updater:installing',         (_, d) => cb(d)),
  onUpdateInstalled:  (cb) => ipcRenderer.on('updater:installed',          (_, d) => cb(d)),
  onUpdateError:      (cb) => ipcRenderer.on('updater:error',              (_, d) => cb(d)),
  onUpToDate:         (cb) => ipcRenderer.on('updater:up-to-date',         (_, d) => cb(d)),
  platform: process.platform,
  isElectron: true,
});
